- name: openai/claude-3.5-sonnet-20241022
  accepts_images: true
  cache_control: true
  caches_by_default: false
  edit_format: diff
  editor_edit_format: editor-diff
  editor_model_name: openai/claude-3.5-sonnet
  examples_as_sys_msg: true
  extra_params:
    extra_headers:
      anthropic-beta: prompt-caching-2024-07-31
    max_tokens: 8192
  lazy: false
  reminder: user
  send_undo_reply: false
  streaming: true
  use_repo_map: true
  use_system_prompt: true
  use_temperature: true
  weak_model_name: "openai/ghc-4o"

- name: openai/claude-3.5-sonnet
  accepts_images: true
  cache_control: true
  caches_by_default: false
  edit_format: diff
  editor_edit_format: editor-diff
  editor_model_name: openai/claude-3.5-sonnet
  examples_as_sys_msg: true
  extra_params:
    extra_headers:
      anthropic-beta: prompt-caching-2024-07-31
    max_tokens: 8192
  lazy: false
  reminder: user
  send_undo_reply: false
  streaming: true
  use_repo_map: true
  use_system_prompt: true
  use_temperature: true
  weak_model_name: "openai/ghc-4o"

- name: openai/ghc-4o
  cache_control: false
  caches_by_default: false
  edit_format: diff
  editor_edit_format: editor-diff
  editor_model_name: openai/ghc-4o
  examples_as_sys_msg: false
  extra_params: null
  lazy: true
  name: openai/gpt-4o
  reminder: sys
  send_undo_reply: false
  streaming: true
  use_repo_map: true
  use_system_prompt: true
  use_temperature: true
  edit_format: "diff"
  weak_model_name: "openai/ghc-4o"
  use_repo_map: true
  examples_as_sys_msg: true
  accepts_images: false